### ISSUE TITLE
Uhhh, the website isn't there?

### ISSUE THREAD

**Issue by peterodavies27atgmailcom** [Compliance-Mods/faithful-mods.github.io#7]
I love this website and I had it bookmarked, but when I got there there was a 404 error. I went to this to see if you changed the address, but your link goes to that page too. Is this dead?

**Comment by verisimal** [comment]
merged with the compliancepack.net website

**Comment by Juknum** [comment]
What was the url ?

**Comment by peterodavies27atgmailcom** [comment]
The url was https://faithful-mods.github.io, and thank you so much.
